### ISSUE TITLE
battray finds "no battery present" on Dell M3800 running Fedora 25 (works fine on Dell XPS13)

### ISSUE THREAD

**Issue by maitra** [Carpetsmoker/battray#1]
Battray on my Dell XPS 13 works just fine on Fedora 25 but not on my Dell M3800. In the latter case, I get a "No battery present" when I mouse over the icon. Not sure what I can investigate or file in the bug report. There are no messages on the console.

**Comment by arp242** [comment]
Ugh, for some reason I'm not getting notifications for some of my projects :-/

Anyway, on Linux it gets its information either from `/sys/class/power_supply/BAT0` or from UPower through DBUS.

Is there anything in `/sys/class/power_supply/`?

As for UPower, make sure you have the `dbus` module installed (`pip install dbus-python`). I just made a change which makes it print a warning if the `dbus` module isn't found, but previously that would be silently ignored.

**Comment by maitra** [comment]
Martin,

Thanks! 

/sys/class/power_supply/ has in it a BAT1 but not a BAT0. 

Btw, I have it packaged for submission to Fedora repos, but it is missing a LICENSE file: could you please add a separate file called LICENSE or COPYING with the license (I guess MIT). Then I can submit it and it can be an official Fedora/RHEL package. 

Many thanks again and best wishes,
Ranjan

**Comment by arp242** [comment]
>  /sys/class/power_supply/ has in it a BAT1 but not a BAT0.

Right, I just made a change so that it'll use the first battery that the system has. Could you verify that this fixes it for you? If it does I can release a new version.

>  I have it packaged for submission to Fedora repos, but it is missing a LICENSE file

Thanks, I added a LICENSE file.

FYI I also added it in pip: https://pypi.python.org/pypi/battray – I never emailed you back because I didn't get around to actually testing the answer to your question >_< I'll send you an email in a minute.

**Comment by maitra** [comment]
Martin,


Thanks again for looking into this.

On Thu, 05 Jan 2017 06:43:49 -0800 Martin Tournoij <notifications@github.com> wrote:

> >  /sys/class/power_supply/ has in it a BAT1 but not a BAT0.
> 
> Right, I just made a change so that it'll use the first battery that the system has. Could you verify that this fixes it for you? If it does I can release a new version.

I am sorry but this does not fix it. I am not sure what sort of error messages to look at. But I still get Battery not present on the Dell M3800. However, battery is present and is found using xfce-power-manager, etc.

Thanks again!
Ranjan

**Comment by arp242** [comment]
Bummer :-(

Looking over the code again, I just made another fix (upower would never be tried). You can try that.

If that doesn't fix it, then unfortunately there's not a whole lot I can do here; as you've already observed yourself it does work on *some* Linux systems. I'm not sure why it doesn't work on your Fedora machine, and it's difficult for me to find out since I don't have access to this system.

The code for this can be found in the [`platforms.py`](https://github.com/Carpetsmoker/battray/blob/master/battray/platforms.py#L121) file. You can try debugging this yourself if you're familiar with basic programming.

**Comment by maitra** [comment]
Martin,

Where should I pick the tar.gz up from, in order to test? From pypi or github?

Many thanks,
Ranjan

**Comment by arp242** [comment]
>  Where should I pick the tar.gz up from, in order to test? From pypi or github?

I haven't updated pypi, you can download master from GitHub, either by cloning the git repo or as a tar.gz: https://github.com/Carpetsmoker/battray/archive/master.tar.gz

And then just run `./battray.py`.

**Comment by maitra** [comment]
Martin,

Sorry for the delay in getting back to you. Here is what I get:


$ ./battray.py 
battray error: [Errno 21] Is a directory: '/sys/class/power_supply/BAT1'

A spot opens up on the system tray, but there is nothing there.

Btw, I went back and looked at the previous version (before you issued the following fix). The following was the error message:

No battery detected (running as username, which is needed to access X). 

In this case, the battery did come up but it was grayed out.

**Comment by arp242** [comment]
>  $ ./battray.py
> battray error: [Errno 21] Is a directory: '/sys/class/power_supply/BAT1'

Okay, this should be fixed now.

It's a bit difficult to fix, as I can't really test this as I don't have a Linux laptop at the moment >_<

**Comment by maitra** [comment]
Hi,

Thanks again and sorry for the delay in getting back to you. There is now a new error:

battray error: [Errno 20] Not a directory: '/sys/class/power_supply/BAT1/status/status'

So, it appears that there is an extra "status"?

BTW:

$ more /sys/class/power_supply/BAT1/status
Full

Many thanks again for looking into this so many times!

Best wishes,
Ranjan


On Tue, 17 Jan 2017 08:41:48 -0800 Martin Tournoij <notifications@github.com> wrote:

> >  $ ./battray.py
> > battray error: [Errno 21] Is a directory: '/sys/class/power_supply/BAT1'
> 
> Okay, this should be fixed now.
> 
> It's a bit difficult to fix, as I can't really test this as I don't have a Linux laptop at the moment >_<
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Carpetsmoker/battray/issues/1#issuecomment-273223994
-- 
Ranjan Maitra <maitra@gmx.com>
