### ISSUE TITLE
Request for 2.3 release

### ISSUE THREAD

**Issue by ghost** [Carpetsmoker/battray#4]
Hello,

Would you be able to make a new release of the current master branch? As discussed in #3, it would make things work for the port in Freebsd.

Kind regards,
M.

**Comment by arp242** [comment]
Yeah, sure. I'll get a new release out soon. Just want to check something before I do.

**Comment by arp242** [comment]
Just had to fix Linux support because I knew that didn't quite work right on newer systems. Version 2.3 is now on PyPi.

**Comment by ghost** [comment]
Very much appreciated. This tool works great!
